modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/IntercraftMC/IntercraftCore/issues"

[[mods]]
    modId="intercraftcore"
    version="${file.jarVersion}"
    displayName="Intercraft Core"
    authors="Coding by: Simon, SirDavidLudwig. Art by Bluefier42"
    description="Core mod for Intercraft 1.13.2 modpack."